<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>q</string>
	</array>
	<key>name</key>
	<string>q</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>/
</string>
			<key>comment</key>
			<string>comment block</string>
			<key>end</key>
			<string>\\
</string>
			<key>name</key>
			<string>comment.block.source.q</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>comment exit</string>
			<key>match</key>
			<string>\s/.*|^/.*</string>
			<key>name</key>
			<string>comment.line.source.q</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\\
</string>
			<key>comment</key>
			<string>string</string>
			<key>end</key>
			<string>\\
</string>
			<key>name</key>
			<string>comment.block.source.q</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.function.q</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>q Reserved Functions</string>
			<key>match</key>
			<string>(?=(\W|\b))((\.Q\.\w+)|(\.z\.\w+)|(\\\w+))(?=(\W|\b))</string>
			<key>name</key>
			<string>other.source.q</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>string</string>
			<key>match</key>
			<string>".*?"</string>
			<key>name</key>
			<string>string.quoted.string.source.q</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>string</string>
			<key>match</key>
			<string>`[:/a-zA-Z0-9_.]+</string>
			<key>name</key>
			<string>string.interpolated.symbol.source.q</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.complex.source.q</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>support.function.q</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Variable Definition</string>
			<key>match</key>
			<string>(?=([^a-zA-Z0-9]|\b))(\.?[a-zA-Z]+[a-zA-Z0-9_\.]*\s*)(:)\s*</string>
			<key>name</key>
			<string>other.source.q</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>q adverbs and shortcut</string>
			<key>match</key>
			<string>[!$@\\/_#?|',`(\\:)]</string>
			<key>name</key>
			<string>support.function.q</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>dot notation</string>
			<key>match</key>
			<string>\.(?=\W)</string>
			<key>name</key>
			<string>support.function.q</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\{\s*\[)</string>
			<key>contentName</key>
			<string>meta.function.parameters.q</string>
			<key>end</key>
			<string>(?=\]\s*)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.other.inherited-class.q</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.parameters.q</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b([a-zA-Z_][a-zA-Z_0-9]*)\s*(?:(;)|(?=[\]\)]))</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.complex.source.q</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>q keywords</string>
			<key>match</key>
			<string>(?=(\W|\b))(prd|while|wavg|delete|min|like|exp|abs|insert|wsum|last|log|div|cos|sin|sqrt|max|in|exec|within|xexp|avg|second|hour|minute|update|sum|by|from|select|neg|not|null|string|reciprocal|floor|ceiling|signum|mod|xbar|xlog|and|or|each|scan|over|prior|mmu|lsq|inv|md5|ltime|gtime|count|first|var|dev|med|cov|cor|all|any|rand|sums|prds|mins|maxs|fills|deltas|ratios|avgs|differ|prev|next|rank|reverse|iasc|idesc|asc|desc|msum|mcount|mavg|mdev|xrank|mmin|mmax|xprev|rotate|distinct|group|where|flip|type|key|til|get|value|attr|cut|set|upsert|raze|union|inter|except|cross|sv|vs|sublist|enlist|read0|read1|hopen|hclose|hdel|hsym|hcount|peach|system|ltrim|rtrim|trim|lower|upper|ssr|view|tables|views|cols|xcols|keys|xkey|xcol|xasc|xdesc|fkeys|meta|lj|aj|aj0|ij|pj|asof|uj|ww|wj|wj1|fby|xgroup|ungroup|ej|save|load|rsave|rload|show|csv|parse|eval)(?=(\W|\b))</string>
			<key>name</key>
			<string>other.source.q</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.complex.source.q</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>datetime</string>
			<key>match</key>
			<string>(?=(\W|\b))([0-9]{4}\.[0-9]{2}\.[0-9]{2}[TD]?[0-9]{2}:[0-9]{2}:[0-9]{2}(:[0-9]{2})?(\.[0-9]{3,6})?)(?=(\W|\b))</string>
			<key>name</key>
			<string>other.source.q</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.complex.source.q</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>time</string>
			<key>match</key>
			<string>(?=(\W|\b))([0-9]{4}\.[0-9]{2}\.[0-9]{2}[TD]?)(?=(\W|\b))</string>
			<key>name</key>
			<string>other.source.q</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.complex.source.q</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>date</string>
			<key>match</key>
			<string>(?=(\W|\b))([0-9]{2}:[0-9]{2}:[0-9]{2}(:[0-9]{2})?(\.[0-9]{3,6})?)(?=(\W|\b))</string>
			<key>name</key>
			<string>other.source.q</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.complex.source.q</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>boolean,short,integer,long</string>
			<key>match</key>
			<string>(?=(\W|\b))([-]?[0-9]+[bhijef]{0,1}(\.[0-9]+[m]?)?|0x[a-f0-9]+)(?=(\W|\b))</string>
			<key>name</key>
			<string>other.source.q</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.q</string>
	<key>uuid</key>
	<string>ef19f88f-c8f2-4877-a39b-68259fdd0ded</string>
</dict>
</plist>
